---
- name: Ensure gpg is present
  ansible.builtin.apt:
    pkg: gnupg
    update_cache: True

- name: Ensure tor is installed
  ansible.builtin.apt:
    pkg: tor
    state: "{{ onion_tor_apt_state }}"

- name: Install extra tor packages
  ansible.builtin.apt:
    pkg: "{{ onion_apt_packages }}"
    state: present

- name: Ensure onion directory is present
  ansible.builtin.file:
    path: "/var/lib/tor/{{ item.key }}/"
    owner: debian-tor
    group: debian-tor
    mode: "0700"
    state: directory
  with_dict: "{{ onion_services }}"
  when: item.value.onion_state|default('present') == 'present'
  notify: Restart tor

- name: Ensure onion configuration is latest
  ansible.builtin.template:
    src: torrc.j2
    dest: /etc/tor/torrc
    owner: root
    group: root
    mode: 0644
  notify: Restart tor

- name: Ensure hostname file are present
  ansible.builtin.template:
    src: hostname.j2
    dest: "/var/lib/tor/{{ item.key }}/hostname"
    owner: debian-tor
    group: debian-tor
    mode: "0600"
    backup: yes
  with_dict: "{{ onion_services }}"
  when:
    - item.value.onion_hostname is defined
    - item.value.onion_hostname
    - item.value.onion_state|default('present') == 'present'
  notify: Restart tor

- name: Copy encoded public_key (only for onion v3)
  ansible.builtin.shell:
    cmd: "set -o pipefail &&\
      echo \"{{ item.value.onion_public_key_b64encoded }}\" | base64 -d >/var/lib/tor/{{ item.key }}/hs_ed25519_public_key"
    executable: /bin/bash
    creates: "/var/lib/tor/{{ item.key }}/hs_ed25519_public_key"
  with_dict: "{{ onion_services }}"
  when:
    - item.value.onion_public_key_b64encoded is defined
    - item.value.onion_public_key_b64encoded
    - item.value.onion_state|default('present') == 'present'
  notify: Restart tor

- name: Ensure file permissions are correct
  ansible.builtin.file:
    path: "/var/lib/tor/{{ item.key }}/hs_ed25519_public_key"
    owner: debian-tor
    group: debian-tor
    mode: 0600
  with_dict: "{{ onion_services }}"
  when:
    - item.value.onion_public_key_b64encoded is defined
    - item.value.onion_public_key_b64encoded
    - item.value.onion_state|default('present') == 'present'

- name: Copy encoded secret_key (only for onion v3)
  ansible.builtin.shell:
    cmd: "set -o pipefail &&\
      echo \"{{ item.value.onion_secret_key_b64encoded }}\" | base64 -d >/var/lib/tor/{{ item.key }}/hs_ed25519_secret_key"
    executable: /bin/bash
    creates: "/var/lib/tor/{{ item.key }}/hs_ed25519_secret_key"
  with_dict: "{{ onion_services }}"
  when:
    - item.value.onion_secret_key_b64encoded is defined
    - item.value.onion_secret_key_b64encoded
    - item.value.onion_state|default('present') == 'present'
  notify: Restart tor

- name: Ensure file permissions are correct
  ansible.builtin.file:
    path: "/var/lib/tor/{{ item.key }}/hs_ed25519_secret_key"
    owner: debian-tor
    group: debian-tor
    mode: "0600"
  with_dict: "{{ onion_services }}"
  when:
    - item.value.onion_secret_key_b64encoded is defined
    - item.value.onion_secret_key_b64encoded
    - item.value.onion_state|default('present') == 'present'

- name: Ensure onion directory is absent
  ansible.builtin.file:
    path: "/var/lib/tor/{{ item.key }}/"
    mode: "0700"
    state: absent
  with_dict: "{{ onion_services }}"
  when: item.value.onion_state|default('present') == "absent"

# The hostname file won't be created until the tor service
# is restarted, so bounce it before the `wait_for` task.
- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Wait for onion
  ansible.builtin.wait_for:
    path: "/var/lib/tor/{{ item.key }}/hostname"
  with_dict: "{{ onion_services }}"
  when: item.value.onion_state|default('present') != "absent"

- name: Read onion url
  ansible.builtin.command: cat "/var/lib/tor/{{ item.key }}/hostname"
  register: onion_hostname_results
  changed_when: false
  with_dict: "{{ onion_services }}"
  when:
    - not item.value.onion_hostname|default(false)
    - item.value.onion_state|default('present') != "absent"

- name: Read onion v3 secret key
  ansible.builtin.command: base64 "/var/lib/tor/{{ item.key }}/hs_ed25519_secret_key"
  register: onion_v3_secret_key_results
  changed_when: false
  with_dict: "{{ onion_services }}"
  when:
    - not item.value.onion_secret_key_b64encoded|default(false)
    - item.value.onion_state|default('present') != "absent"

- name: Read onion v3 public key
  ansible.builtin.command: base64 "/var/lib/tor/{{ item.key }}/hs_ed25519_public_key"
  register: onion_v3_public_key_results
  changed_when: false
  with_dict: "{{ onion_services }}"
  when:
    - not item.value.onion_public_key_b64encoded|default(false)
    - item.value.onion_state|default('present') != "absent"

- name: Display onion url
  ansible.builtin.debug:
    msg: >-
      {{ lookup('template', role_path + '/templates/display_hostnames.j2') }}

- name: Display public key for v3 host
  ansible.builtin.debug:
    msg: >-
      {{ lookup('template', role_path + '/templates/display_v3_public_keys.j2') }}

- name: Display secret key for v3 host
  ansible.builtin.debug:
    msg: >-
      {{ lookup('template', role_path + '/templates/display_v3_secret_keys.j2') }}

# dirty hack to stop tor, when server is not the current onion server,
# restart handler above , would start tor with
# same url and private key on two hosts
- name: Stop tor, (two servers are up, only one should act as HS)
  ansible.builtin.systemd:
    name: tor
    enabled: no
    state: stopped
  notify: Stop tor
  when: not onion_active

- name: Import monit tasks
  ansible.builtin.import_tasks: monit.yml
  when: onion_monit_enabled

- name: Import goss tasks
  ansible.builtin.import_tasks: goss.yml
  tags:
    - goss
